/* fdpstype.c -- the game record layouts, measured as the compiler
 * built them.
 *
 * GENERATED by tools/code_emit/gen_types.py alongside src/fdpstype.h.
 * Do not edit by hand.
 *
 * Expected values come from ghidra_snapshot/data_types.txt, which is
 * ticket 17's reading of the original's own field offsets -- not from
 * the header, which would only prove the header equals itself.
 */
#include <stddef.h>
#include "testharn.h"
#include "fdpstype.h"

static void t_fdps_cd_q_channel_block(void)
{
    CHECK_EQ((int) sizeof(struct fdps_cd_q_channel_block), 11);
    CHECK_EQ((int) offsetof(struct fdps_cd_q_channel_block, control_code), 0);
    CHECK_EQ((int) offsetof(struct fdps_cd_q_channel_block, control_adr), 1);
    CHECK_EQ((int) offsetof(struct fdps_cd_q_channel_block, track_number), 2);
    CHECK_EQ((int) offsetof(struct fdps_cd_q_channel_block, point_index), 3);
    CHECK_EQ((int) offsetof(struct fdps_cd_q_channel_block, minute), 4);
    CHECK_EQ((int) offsetof(struct fdps_cd_q_channel_block, second), 5);
    CHECK_EQ((int) offsetof(struct fdps_cd_q_channel_block, frame), 6);
    CHECK_EQ((int) offsetof(struct fdps_cd_q_channel_block, zero), 7);
    CHECK_EQ((int) offsetof(struct fdps_cd_q_channel_block, absolute_minute), 8);
    CHECK_EQ((int) offsetof(struct fdps_cd_q_channel_block, absolute_second), 9);
    CHECK_EQ((int) offsetof(struct fdps_cd_q_channel_block, absolute_frame), 10);
}

static void t_fdps_cd_request_header(void)
{
    CHECK_EQ((int) sizeof(struct fdps_cd_request_header), 26);
    CHECK_EQ((int) offsetof(struct fdps_cd_request_header, header_length), 0);
    CHECK_EQ((int) offsetof(struct fdps_cd_request_header, subunit), 1);
    CHECK_EQ((int) offsetof(struct fdps_cd_request_header, command), 2);
    CHECK_EQ((int) offsetof(struct fdps_cd_request_header, status), 3);
    CHECK_EQ((int) offsetof(struct fdps_cd_request_header, reserved), 5);
    CHECK_EQ((int) offsetof(struct fdps_cd_request_header, media_descriptor), 13);
    CHECK_EQ((int) offsetof(struct fdps_cd_request_header, transfer_address), 14);
    CHECK_EQ((int) offsetof(struct fdps_cd_request_header, transfer_byte_count), 18);
    CHECK_EQ((int) offsetof(struct fdps_cd_request_header, start_sector), 20);
    CHECK_EQ((int) offsetof(struct fdps_cd_request_header, volume_id_ptr), 22);
}

static void t_fdps_cel_cache_slot(void)
{
    CHECK_EQ((int) sizeof(struct fdps_cel_cache_slot), 48);
    CHECK_EQ((int) offsetof(struct fdps_cel_cache_slot, sprite_offset), 0);
}

static void t_fdps_cel_header(void)
{
    CHECK_EQ((int) sizeof(struct fdps_cel_header), 15);
    CHECK_EQ((int) offsetof(struct fdps_cel_header, magic), 0);
    CHECK_EQ((int) offsetof(struct fdps_cel_header, version), 3);
    CHECK_EQ((int) offsetof(struct fdps_cel_header, sprite_table_offset), 5);
    CHECK_EQ((int) offsetof(struct fdps_cel_header, sprite_width), 7);
    CHECK_EQ((int) offsetof(struct fdps_cel_header, sprite_height), 9);
    CHECK_EQ((int) offsetof(struct fdps_cel_header, sprite_count), 11);
    CHECK_EQ((int) offsetof(struct fdps_cel_header, pixel_encoding), 13);
}

static void t_fdps_char_spawn_record(void)
{
    CHECK_EQ((int) sizeof(struct fdps_char_spawn_record), 26);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, side), 0);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, char_id), 1);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, level), 4);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, equipped_item_0), 5);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, equipped_item_1), 6);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, carried_items), 7);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, spell_mask), 13);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, ai_class), 17);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, ai_dest_x), 18);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, ai_dest_y), 19);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, cell_event_code), 20);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, wave_no), 21);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, death_script_opcode), 22);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, death_script_operand), 23);
    CHECK_EQ((int) offsetof(struct fdps_char_spawn_record, spell_mask_high), 25);
}

static void t_fdps_character_base_record(void)
{
    CHECK_EQ((int) sizeof(struct fdps_character_base_record), 24);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, race_id), 0);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, class_id), 1);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, level), 2);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, hp_base), 3);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, mp_base), 5);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, move), 7);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, spell_mask), 8);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, equipped_item_0), 12);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, equipped_item_1), 13);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, carried_items), 14);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, ap_base), 18);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, dp_base), 20);
    CHECK_EQ((int) offsetof(struct fdps_character_base_record, dx_base), 22);
}

static void t_fdps_character_growth(void)
{
    CHECK_EQ((int) sizeof(struct fdps_character_growth), 11);
    CHECK_EQ((int) offsetof(struct fdps_character_growth, ap_min), 0);
    CHECK_EQ((int) offsetof(struct fdps_character_growth, ap_max), 1);
    CHECK_EQ((int) offsetof(struct fdps_character_growth, dp_min), 2);
    CHECK_EQ((int) offsetof(struct fdps_character_growth, dp_max), 3);
    CHECK_EQ((int) offsetof(struct fdps_character_growth, dx_min), 4);
    CHECK_EQ((int) offsetof(struct fdps_character_growth, dx_max), 5);
    CHECK_EQ((int) offsetof(struct fdps_character_growth, hp_min), 6);
    CHECK_EQ((int) offsetof(struct fdps_character_growth, hp_max), 7);
    CHECK_EQ((int) offsetof(struct fdps_character_growth, mp_min), 8);
    CHECK_EQ((int) offsetof(struct fdps_character_growth, mp_max), 9);
    CHECK_EQ((int) offsetof(struct fdps_character_growth, spell_learning_idx), 10);
}

static void t_fdps_class_equip_record(void)
{
    CHECK_EQ((int) sizeof(struct fdps_class_equip_record), 6);
    CHECK_EQ((int) offsetof(struct fdps_class_equip_record, allowed_item_type), 0);
}

static void t_fdps_class_record(void)
{
    CHECK_EQ((int) sizeof(struct fdps_class_record), 10);
    CHECK_EQ((int) offsetof(struct fdps_class_record, move_cost), 0);
    CHECK_EQ((int) offsetof(struct fdps_class_record, critical), 8);
    CHECK_EQ((int) offsetof(struct fdps_class_record, magic_resist_complement), 9);
}

static void t_fdps_dpmi_real_mode_call(void)
{
    CHECK_EQ((int) sizeof(struct fdps_dpmi_real_mode_call), 50);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, edi), 0);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, esi), 4);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, ebp), 8);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, reserved_by_system), 12);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, ebx), 16);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, edx), 20);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, ecx), 24);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, eax), 28);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, flags), 32);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, es), 34);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, ds), 36);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, fs), 38);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, gs), 40);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, ip), 42);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, cs), 44);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, sp), 46);
    CHECK_EQ((int) offsetof(struct fdps_dpmi_real_mode_call, ss), 48);
}

static void t_fdps_enemy_data(void)
{
    CHECK_EQ((int) sizeof(struct fdps_enemy_data), 10);
    CHECK_EQ((int) offsetof(struct fdps_enemy_data, race_id), 0);
    CHECK_EQ((int) offsetof(struct fdps_enemy_data, class_id), 1);
    CHECK_EQ((int) offsetof(struct fdps_enemy_data, hp), 2);
    CHECK_EQ((int) offsetof(struct fdps_enemy_data, mp), 4);
    CHECK_EQ((int) offsetof(struct fdps_enemy_data, ap), 5);
    CHECK_EQ((int) offsetof(struct fdps_enemy_data, dp), 6);
    CHECK_EQ((int) offsetof(struct fdps_enemy_data, dx), 7);
    CHECK_EQ((int) offsetof(struct fdps_enemy_data, mv), 8);
    CHECK_EQ((int) offsetof(struct fdps_enemy_data, exp_reward), 9);
}

static void t_fdps_item_effect(void)
{
    CHECK_EQ((int) sizeof(struct fdps_item_effect), 23);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, type), 0);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, ap), 1);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, hit), 3);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, dp), 5);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, ev), 7);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, hit_effect), 9);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, hit_effect_rate), 10);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, range_min), 11);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, range_max), 12);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, use_effect), 13);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, use_amount), 14);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, use_distance), 16);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, use_target), 17);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, use_radius), 18);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, price), 19);
    CHECK_EQ((int) offsetof(struct fdps_item_effect, select_mode), 21);
}

static void t_fdps_map_cell_code_layer(void)
{
    CHECK_EQ((int) sizeof(struct fdps_map_cell_code_layer), 17);
    CHECK_EQ((int) offsetof(struct fdps_map_cell_code_layer, magic), 0);
    CHECK_EQ((int) offsetof(struct fdps_map_cell_code_layer, version), 4);
    CHECK_EQ((int) offsetof(struct fdps_map_cell_code_layer, table_offset), 5);
    CHECK_EQ((int) offsetof(struct fdps_map_cell_code_layer, width), 7);
    CHECK_EQ((int) offsetof(struct fdps_map_cell_code_layer, height), 9);
    CHECK_EQ((int) offsetof(struct fdps_map_cell_code_layer, layer_count), 11);
    CHECK_EQ((int) offsetof(struct fdps_map_cell_code_layer, layer_ids), 14);
    CHECK_EQ((int) offsetof(struct fdps_map_cell_code_layer, cells), 16);
}

static void t_fdps_map_spawn_pos_record(void)
{
    CHECK_EQ((int) sizeof(struct fdps_map_spawn_pos_record), 6);
    CHECK_EQ((int) offsetof(struct fdps_map_spawn_pos_record, char_id), 0);
    CHECK_EQ((int) offsetof(struct fdps_map_spawn_pos_record, desired_x), 2);
    CHECK_EQ((int) offsetof(struct fdps_map_spawn_pos_record, desired_y), 4);
}

static void t_fdps_move_grid_cell(void)
{
    CHECK_EQ((int) sizeof(struct fdps_move_grid_cell), 2);
    CHECK_EQ((int) offsetof(struct fdps_move_grid_cell, flags), 0);
    CHECK_EQ((int) offsetof(struct fdps_move_grid_cell, marker), 1);
}

static void t_fdps_palette_entry(void)
{
    CHECK_EQ((int) sizeof(struct fdps_palette_entry), 3);
    CHECK_EQ((int) offsetof(struct fdps_palette_entry, red), 0);
    CHECK_EQ((int) offsetof(struct fdps_palette_entry, green), 1);
    CHECK_EQ((int) offsetof(struct fdps_palette_entry, blue), 2);
}

static void t_fdps_promotion_record(void)
{
    CHECK_EQ((int) sizeof(struct fdps_promotion_record), 12);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, default_portrait_id), 0);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, default_class_id), 1);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, default_move_bonus), 2);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, light_badge_portrait_id), 3);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, light_badge_class_id), 4);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, light_badge_move_bonus), 5);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, dark_badge_portrait_id), 6);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, dark_badge_class_id), 7);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, dark_badge_move_bonus), 8);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, hero_badge_portrait_id), 9);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, hero_badge_class_id), 10);
    CHECK_EQ((int) offsetof(struct fdps_promotion_record, hero_badge_move_bonus), 11);
}

static void t_fdps_spell_effect(void)
{
    CHECK_EQ((int) sizeof(struct fdps_spell_effect), 7);
    CHECK_EQ((int) offsetof(struct fdps_spell_effect, power), 0);
    CHECK_EQ((int) offsetof(struct fdps_spell_effect, hit_rate), 2);
    CHECK_EQ((int) offsetof(struct fdps_spell_effect, cast_range_flags), 3);
    CHECK_EQ((int) offsetof(struct fdps_spell_effect, area), 4);
    CHECK_EQ((int) offsetof(struct fdps_spell_effect, mp_cost), 5);
    CHECK_EQ((int) offsetof(struct fdps_spell_effect, target_side), 6);
}

static void t_fdps_spell_learning_record(void)
{
    CHECK_EQ((int) sizeof(struct fdps_spell_learning_record), 12);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, lv_0), 0);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, spell_id_0), 1);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, lv_1), 2);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, spell_id_1), 3);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, lv_2), 4);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, spell_id_2), 5);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, lv_3), 6);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, spell_id_3), 7);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, lv_4), 8);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, spell_id_4), 9);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, lv_5), 10);
    CHECK_EQ((int) offsetof(struct fdps_spell_learning_record, spell_id_5), 11);
}

static void t_fdps_tile_attr_entry(void)
{
    CHECK_EQ((int) sizeof(struct fdps_tile_attr_entry), 4);
    CHECK_EQ((int) offsetof(struct fdps_tile_attr_entry, flags), 0);
    CHECK_EQ((int) offsetof(struct fdps_tile_attr_entry, blend_level), 1);
    CHECK_EQ((int) offsetof(struct fdps_tile_attr_entry, terrain_type), 2);
    CHECK_EQ((int) offsetof(struct fdps_tile_attr_entry, combat_backdrop_id), 3);
}

static void t_fdps_unit_record(void)
{
    CHECK_EQ((int) sizeof(struct fdps_unit_record), 80);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, pos_x), 0);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, pos_y), 1);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, sprite_cache_slot), 2);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, facing), 3);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, walk_step), 4);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, flags), 5);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, side), 6);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, portrait_id), 7);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, char_id), 8);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, reserved_09), 9);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, inventory_slots), 10);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, spells_known_bitmap), 26);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, race), 31);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, clazz), 32);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, level), 33);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, status_timers), 34);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, death_script_opcode), 49);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, death_script_operand), 50);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, ai_behavior), 52);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, ai_dest_x), 53);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, ai_dest_y), 54);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, ap_base), 55);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, dp_base), 57);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, move), 59);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, exp_carry), 60);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, event_slot), 61);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, dx_base), 62);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, hp_current), 64);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, hp_max), 66);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, mp_current), 68);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, mp_max), 70);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, ap), 72);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, dp), 74);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, hit), 76);
    CHECK_EQ((int) offsetof(struct fdps_unit_record, ev), 78);
}

static void t_fdps_vfs_image_header(void)
{
    CHECK_EQ((int) sizeof(struct fdps_vfs_image_header), 11);
    CHECK_EQ((int) offsetof(struct fdps_vfs_image_header, magic), 0);
    CHECK_EQ((int) offsetof(struct fdps_vfs_image_header, version), 3);
    CHECK_EQ((int) offsetof(struct fdps_vfs_image_header, entry_table_offset), 5);
    CHECK_EQ((int) offsetof(struct fdps_vfs_image_header, entry_count), 7);
}

static void t_fdps_save_slot(void)
{
    CHECK_EQ((int) sizeof(struct fdps_save_slot), 2600);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, roster), 0);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, bonus_lottery_drawn_flag), 2540);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, save_minute), 2544);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, save_hour), 2548);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, save_day), 2552);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, save_month), 2556);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, chapter_index), 2560);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, roster_member_count), 2561);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, party_gold), 2562);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, terrain_hud_user_enabled), 2566);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, battle_animation_enabled), 2567);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, bgm_enabled_flag), 2568);
    CHECK_EQ((int) offsetof(struct fdps_save_slot, sfx_enabled_flag), 2569);
}

void run_fdpstype_tests(void)
{
    RUN_TEST(t_fdps_cd_q_channel_block);
    RUN_TEST(t_fdps_cd_request_header);
    RUN_TEST(t_fdps_cel_cache_slot);
    RUN_TEST(t_fdps_cel_header);
    RUN_TEST(t_fdps_char_spawn_record);
    RUN_TEST(t_fdps_character_base_record);
    RUN_TEST(t_fdps_character_growth);
    RUN_TEST(t_fdps_class_equip_record);
    RUN_TEST(t_fdps_class_record);
    RUN_TEST(t_fdps_dpmi_real_mode_call);
    RUN_TEST(t_fdps_enemy_data);
    RUN_TEST(t_fdps_item_effect);
    RUN_TEST(t_fdps_map_cell_code_layer);
    RUN_TEST(t_fdps_map_spawn_pos_record);
    RUN_TEST(t_fdps_move_grid_cell);
    RUN_TEST(t_fdps_palette_entry);
    RUN_TEST(t_fdps_promotion_record);
    RUN_TEST(t_fdps_spell_effect);
    RUN_TEST(t_fdps_spell_learning_record);
    RUN_TEST(t_fdps_tile_attr_entry);
    RUN_TEST(t_fdps_unit_record);
    RUN_TEST(t_fdps_vfs_image_header);
    RUN_TEST(t_fdps_save_slot);
}
