/* ailv3.h - Miles AIL Audio Interface Library v3 (rebuilt from FD2.LE)
 * Target  : Watcom C/C++ 9.5a, DOS/4G LE 32-bit flat
 * Source  : auto-generated by tools/ail_extract/gen_ailv3_h.py from
 *           workspace/ail_extract/ail_inventory.json -- DO NOT EDIT.
 *
 * Signature notes
 *   - `__cdecl` / `__watcall` keyword follows Ghidra audit of each function.
 *   - `#pragma aux <name> "*"` keeps PUBDEF symbol byte-identical with
 *     `ailv3.lib`. `modify [eax ebx ecx edx]` declares the vendor clobber set
 *     (EBX is clobbered without a PUSH; EAX/ECX/EDX are ordinary volatiles).
 *     The full list is required for -3s clients; a bare [ebx] is unsafe there.
 *   - `param_N` parameter names are Ghidra defaults where the original
 *     C names have not been recovered; clients pass arguments by position.
 */
#ifndef AILV3_H
#define AILV3_H

#ifdef __cplusplus
extern "C" {
#endif

/* Opaque handle typedefs — Miles SDK convention. Internally these are
   pointers to vendor-allocated structs (or small integers for timers).
   In Watcom 32-bit flat model int and void* are both 32-bit, so the
   underlying representation is interchangeable. */
typedef void *       HDIGDRIVER;    /* DIG driver handle (from AIL_install_DIG_*) */
typedef void *       HMDIDRIVER;    /* MDI driver handle (from AIL_install_MDI_*) */
typedef void *       HSAMPLE;       /* sample playback handle */
typedef void *       HSEQUENCE;     /* XMIDI sequence handle */
typedef unsigned int HTIMER;        /* timer slot handle */
typedef void *       HDRIVER;       /* generic driver handle (from AIL_install_driver) */
typedef void *       HWAVESYNTH;    /* wave synthesizer handle */


extern void * __cdecl AIL_API_read_INI(void * out_ioparms, char * ini_path);
#pragma aux AIL_API_read_INI "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_active_sample_count(HDIGDRIVER dig_driver);
#pragma aux AIL_active_sample_count "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_active_sequence_count(HMDIDRIVER mdi_driver);
#pragma aux AIL_active_sequence_count "*" modify [eax ebx ecx edx];

extern HSAMPLE __cdecl AIL_allocate_file_sample(HDIGDRIVER dig_driver, void * file_image, int format);
#pragma aux AIL_allocate_file_sample "*" modify [eax ebx ecx edx];

extern HSAMPLE __cdecl AIL_allocate_sample_handle(HDIGDRIVER dig_driver);
#pragma aux AIL_allocate_sample_handle "*" modify [eax ebx ecx edx];

extern HSEQUENCE __cdecl AIL_allocate_sequence_handle(HMDIDRIVER mdi_driver);
#pragma aux AIL_allocate_sequence_handle "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_branch_index(HSEQUENCE sequence, unsigned int marker_idx);
#pragma aux AIL_branch_index "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_call_driver(int param_1, unsigned int param_2, int param_3, short * param_4);
#pragma aux AIL_call_driver "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_channel_notes(HSEQUENCE sequence, int channel);
#pragma aux AIL_channel_notes "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_controller_value(HSEQUENCE sequence, int channel, int controller);
#pragma aux AIL_controller_value "*" modify [eax ebx ecx edx];

extern HWAVESYNTH __cdecl AIL_create_wave_synthesizer(HDIGDRIVER dig_driver, HMDIDRIVER mdi_driver, void * gtl_data, int polyphony);
#pragma aux AIL_create_wave_synthesizer "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_delay(int param_1);
#pragma aux AIL_delay "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_destroy_wave_synthesizer(void * synth);
#pragma aux AIL_destroy_wave_synthesizer "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_end_sample(HSAMPLE sample);
#pragma aux AIL_end_sample "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_end_sequence(HSEQUENCE sequence);
#pragma aux AIL_end_sequence "*" modify [eax ebx ecx edx];

extern HDRIVER __cdecl AIL_get_IO_environment(HDRIVER driver_handle);
#pragma aux AIL_get_IO_environment "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_get_last_error_code(void);
#pragma aux AIL_get_last_error_code "*" modify [eax ebx ecx edx];

extern unsigned int __cdecl AIL_get_real_vect(unsigned int irq);
#pragma aux AIL_get_real_vect "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_init_sample(HSAMPLE sample);
#pragma aux AIL_init_sample "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_init_sequence(HSEQUENCE sequence, unsigned int xmi_data, int sequence_idx);
#pragma aux AIL_init_sequence "*" modify [eax ebx ecx edx];

extern HDIGDRIVER __cdecl AIL_install_DIG_INI(void);
#pragma aux AIL_install_DIG_INI "*" modify [eax ebx ecx edx];

extern HDIGDRIVER __cdecl AIL_install_DIG_driver_file(char * filename, void * io_parms);
#pragma aux AIL_install_DIG_driver_file "*" modify [eax ebx ecx edx];

extern HDIGDRIVER __cdecl AIL_install_DIG_driver_image(void * image, unsigned int image_size, void * io_parms);
#pragma aux AIL_install_DIG_driver_image "*" modify [eax ebx ecx edx];

extern HMDIDRIVER __cdecl AIL_install_MDI_INI(void);
#pragma aux AIL_install_MDI_INI "*" modify [eax ebx ecx edx];

extern HMDIDRIVER __cdecl AIL_install_MDI_driver_file(char * filename, void * io_parms);
#pragma aux AIL_install_MDI_driver_file "*" modify [eax ebx ecx edx];

extern HMDIDRIVER __cdecl AIL_install_MDI_driver_image(void * image, unsigned int image_size, void * io_parms);
#pragma aux AIL_install_MDI_driver_image "*" modify [eax ebx ecx edx];

extern HDRIVER __cdecl AIL_install_driver(void * image_buf, unsigned int image_size);
#pragma aux AIL_install_driver "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_install_timbre(HSEQUENCE sequence, int bank, int patch);
#pragma aux AIL_install_timbre "*" modify [eax ebx ecx edx];

extern unsigned int __cdecl AIL_interrupt_divisor(void);
#pragma aux AIL_interrupt_divisor "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_load_sample_buffer(HSAMPLE sample, unsigned int buf_idx, void * buf_addr, unsigned int len);
#pragma aux AIL_load_sample_buffer "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_lock_channel(HMDIDRIVER mdi_driver);
#pragma aux AIL_lock_channel "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_map_sequence_channel(HSEQUENCE sequence, int seq_chan, int phys_chan);
#pragma aux AIL_map_sequence_channel "*" modify [eax ebx ecx edx];

extern unsigned int __cdecl AIL_minimum_sample_buffer_size(HDIGDRIVER dig_driver, int rate, int bytes);
#pragma aux AIL_minimum_sample_buffer_size "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_protect_timbre(HSEQUENCE sequence, int bank, int patch);
#pragma aux AIL_protect_timbre "*" modify [eax ebx ecx edx];

extern void * __cdecl AIL_register_EOB_callback(HSAMPLE sample, void * callback);
#pragma aux AIL_register_EOB_callback "*" modify [eax ebx ecx edx];

extern void * __cdecl AIL_register_EOF_callback(HSAMPLE sample, void * callback);
#pragma aux AIL_register_EOF_callback "*" modify [eax ebx ecx edx];

extern void * __cdecl AIL_register_EOS_callback(HSAMPLE sample, void * callback);
#pragma aux AIL_register_EOS_callback "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_register_ICA_array(HSEQUENCE sequence, void * ica_array);
#pragma aux AIL_register_ICA_array "*" modify [eax ebx ecx edx];

extern void * __cdecl AIL_register_SOB_callback(HSAMPLE sample, void * callback);
#pragma aux AIL_register_SOB_callback "*" modify [eax ebx ecx edx];

extern void * __cdecl AIL_register_event_callback(HSEQUENCE sequence, void * callback);
#pragma aux AIL_register_event_callback "*" modify [eax ebx ecx edx];

extern void * __cdecl AIL_register_prefix_callback(HSEQUENCE sequence, void * callback);
#pragma aux AIL_register_prefix_callback "*" modify [eax ebx ecx edx];

extern void * __cdecl AIL_register_sequence_callback(HSEQUENCE sequence, void * callback);
#pragma aux AIL_register_sequence_callback "*" modify [eax ebx ecx edx];

extern void * __cdecl AIL_register_timbre_callback(HMDIDRIVER mdi_driver, void * callback);
#pragma aux AIL_register_timbre_callback "*" modify [eax ebx ecx edx];

extern HTIMER __cdecl AIL_register_timer(unsigned int param_1);
#pragma aux AIL_register_timer "*" modify [eax ebx ecx edx];

extern void * __cdecl AIL_register_trigger_callback(HSEQUENCE sequence, void * callback);
#pragma aux AIL_register_trigger_callback "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_release_all_timers(void);
#pragma aux AIL_release_all_timers "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_release_channel(HMDIDRIVER mdi_driver, int channel);
#pragma aux AIL_release_channel "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_release_sample_handle(HSAMPLE sample);
#pragma aux AIL_release_sample_handle "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_release_sequence_handle(HSEQUENCE sequence);
#pragma aux AIL_release_sequence_handle "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_release_timer_handle(HTIMER timer_handle);
#pragma aux AIL_release_timer_handle "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_restore_USE16_ISR(int irq);
#pragma aux AIL_restore_USE16_ISR "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_resume_sample(HSAMPLE sample);
#pragma aux AIL_resume_sample "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_resume_sequence(HSEQUENCE sequence);
#pragma aux AIL_resume_sequence "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_sample_buffer_ready(HSAMPLE sample);
#pragma aux AIL_sample_buffer_ready "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_sample_loop_count(HSAMPLE sample);
#pragma aux AIL_sample_loop_count "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_sample_pan(HSAMPLE sample);
#pragma aux AIL_sample_pan "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_sample_playback_rate(HSAMPLE sample);
#pragma aux AIL_sample_playback_rate "*" modify [eax ebx ecx edx];

extern unsigned int __cdecl AIL_sample_position(HSAMPLE sample);
#pragma aux AIL_sample_position "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_sample_status(HSAMPLE sample);
#pragma aux AIL_sample_status "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_sample_user_data(HSAMPLE sample, unsigned int slot);
#pragma aux AIL_sample_user_data "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_sample_volume(HSAMPLE sample);
#pragma aux AIL_sample_volume "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_send_channel_voice_message(HMDIDRIVER mdi_driver, int status, int chan, int data1, int data2);
#pragma aux AIL_send_channel_voice_message "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_send_sysex_message(HMDIDRIVER mdi_driver, void * sysex_data);
#pragma aux AIL_send_sysex_message "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_sequence_loop_count(HSEQUENCE sequence);
#pragma aux AIL_sequence_loop_count "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_sequence_position(HSEQUENCE sequence, int * out_beat, int * out_measure);
#pragma aux AIL_sequence_position "*" modify [eax ebx ecx edx];

extern unsigned int __cdecl AIL_sequence_status(HSEQUENCE sequence);
#pragma aux AIL_sequence_status "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_sequence_tempo(HSEQUENCE sequence);
#pragma aux AIL_sequence_tempo "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_sequence_user_data(HSEQUENCE sequence, unsigned int slot);
#pragma aux AIL_sequence_user_data "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_sequence_volume(HSEQUENCE sequence);
#pragma aux AIL_sequence_volume "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_GTL_filename_prefix(char * prefix);
#pragma aux AIL_set_GTL_filename_prefix "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_USE16_ISR(int irq, unsigned int isr_offset, unsigned int flags);
#pragma aux AIL_set_USE16_ISR "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_set_preference(int param_1, unsigned int param_2);
#pragma aux AIL_set_preference "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_real_vect(unsigned int irq, unsigned int isr_addr);
#pragma aux AIL_set_real_vect "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sample_address(HSAMPLE sample, unsigned int start, unsigned int len);
#pragma aux AIL_set_sample_address "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_set_sample_file(HSAMPLE sample, void * file_image, int format);
#pragma aux AIL_set_sample_file "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sample_loop_count(HSAMPLE sample, unsigned int count);
#pragma aux AIL_set_sample_loop_count "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sample_pan(HSAMPLE sample, int pan);
#pragma aux AIL_set_sample_pan "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sample_playback_rate(HSAMPLE sample, int samples_per_sec);
#pragma aux AIL_set_sample_playback_rate "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sample_position(HSAMPLE sample, unsigned int pos);
#pragma aux AIL_set_sample_position "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sample_type(HSAMPLE sample, int format, unsigned int flags);
#pragma aux AIL_set_sample_type "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sample_user_data(HSAMPLE sample, unsigned int slot, int value);
#pragma aux AIL_set_sample_user_data "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sample_volume(HSAMPLE sample, unsigned int volume_0_127);
#pragma aux AIL_set_sample_volume "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sequence_loop_count(HSEQUENCE sequence, unsigned int count);
#pragma aux AIL_set_sequence_loop_count "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sequence_tempo(HSEQUENCE sequence, int tempo, int ramp_ms);
#pragma aux AIL_set_sequence_tempo "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sequence_user_data(HSEQUENCE sequence, unsigned int slot, int value);
#pragma aux AIL_set_sequence_user_data "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_sequence_volume(HSEQUENCE sequence, int target, int ramp_ms);
#pragma aux AIL_set_sequence_volume "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_timer_divisor(HTIMER timer_handle, unsigned int divisor);
#pragma aux AIL_set_timer_divisor "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_timer_frequency(int param_1, unsigned int param_2);
#pragma aux AIL_set_timer_frequency "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_set_timer_period(int param_1, unsigned int param_2);
#pragma aux AIL_set_timer_period "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_set_timer_user(int param_1, unsigned int param_2);
#pragma aux AIL_set_timer_user "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_shutdown(void);
#pragma aux AIL_shutdown "*" modify [eax ebx ecx edx];

extern void AIL_start_all_timers(void);
#pragma aux AIL_start_all_timers "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_start_sample(HSAMPLE sample);
#pragma aux AIL_start_sample "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_start_sequence(HSEQUENCE sequence);
#pragma aux AIL_start_sequence "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_start_timer(int param_1);
#pragma aux AIL_start_timer "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_startup(void);
#pragma aux AIL_startup "*" modify [eax ebx ecx edx];

extern void AIL_stop_all_timers(void);
#pragma aux AIL_stop_all_timers "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_stop_sample(HSAMPLE sample);
#pragma aux AIL_stop_sample "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_stop_sequence(HSEQUENCE sequence);
#pragma aux AIL_stop_sequence "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_stop_timer(int param_1);
#pragma aux AIL_stop_timer "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_timbre_status(HSEQUENCE sequence, unsigned int bank, unsigned int patch);
#pragma aux AIL_timbre_status "*" modify [eax ebx ecx edx];

extern int __cdecl AIL_true_sequence_channel(HSEQUENCE sequence, unsigned int seq_chan);
#pragma aux AIL_true_sequence_channel "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_uninstall_DIG_driver(HDIGDRIVER dig_driver);
#pragma aux AIL_uninstall_DIG_driver "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_uninstall_MDI_driver(HMDIDRIVER mdi_driver);
#pragma aux AIL_uninstall_MDI_driver "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_uninstall_driver(unsigned int * param_1);
#pragma aux AIL_uninstall_driver "*" modify [eax ebx ecx edx];

extern void __cdecl AIL_unprotect_timbre(HSEQUENCE sequence, int bank, int patch);
#pragma aux AIL_unprotect_timbre "*" modify [eax ebx ecx edx];


#ifdef __cplusplus
}
#endif

#endif /* AILV3_H */
