/* fdpstype.h -- the game's own record layouts.
 *
 * GENERATED by tools/code_emit/gen_types.py from
 * ghidra_snapshot/data_types.txt, which is ticket 17's settled answer
 * for every one of these.  Do not edit by hand: fix the layout in
 * Ghidra, re-export the snapshot, and regenerate.
 *
 * What each field means is written on the field in Ghidra and in the
 * knowledge base; it is deliberately not copied here, because a second
 * copy is one that goes stale.
 *
 * Every record is byte-packed.  wcc386's default is already byte
 * packing, but these offsets are the original's and must not depend on
 * a compiler flag staying where it is (rebuild_info/pitfalls.md).
 */
#ifndef FDPSTYPE_H
#define FDPSTYPE_H

#pragma pack(1)

/* MSCDEX Audio Q-Channel Info control block (IOCTL-input code 0x0c): the request byte sent to the CD-ROM driver and the 11-byte reply saying which CD-DA track is playing and how far into it the drive has got. */
struct fdps_cd_q_channel_block {
    unsigned char control_code;
    unsigned char control_adr;
    unsigned char track_number;
    unsigned char point_index;
    unsigned char minute;
    unsigned char second;
    unsigned char frame;
    unsigned char zero;
    unsigned char absolute_minute;
    unsigned char absolute_second;
    unsigned char absolute_frame;
};

/* MSCDEX device-driver request header, in the IOCTL Input/Output shape the game builds on the stack and stages through the DOS conventional-memory block at data_fdps_cd_request_header_buffer. */
struct fdps_cd_request_header {
    unsigned char header_length;
    unsigned char subunit;
    unsigned char command;
    unsigned short status;
    unsigned char reserved[8];
    unsigned char media_descriptor;
    unsigned int transfer_address;
    unsigned short transfer_byte_count;
    unsigned short start_sector;
    unsigned int volume_id_ptr;
};

/* One cached CEL sprite group in the block behind data_fdps_cel_sprite_cache_ptr: twelve base-relative offsets to packed sprite streams, read as four facings of three walk frames for a unit icon set. */
struct fdps_cel_cache_slot {
    int sprite_offset[12];
};

/* CEL sprite-sheet header: the fixed 15 bytes every .cel image opens with, followed immediately at +0x0f by sprite_count+1 u32 stream offsets. */
struct fdps_cel_header {
    char magic[3];
    unsigned short version;
    unsigned short sprite_table_offset;
    short sprite_width;
    short sprite_height;
    short sprite_count;
    unsigned short pixel_encoding;
};

/* One scripted unit deployment from a chapter's MAP%02d.DAT block: who to place, at what level, with what equipment, spells, AI behaviour and on-death reward. */
struct fdps_char_spawn_record {
    unsigned char side;
    unsigned char char_id;
    unsigned char gap_002[2];
    unsigned char level;
    unsigned char equipped_item_0;
    unsigned char equipped_item_1;
    unsigned char carried_items[6];
    unsigned char spell_mask[4];
    unsigned char ai_class;
    unsigned char ai_dest_x;
    unsigned char ai_dest_y;
    unsigned char cell_event_code;
    unsigned char wave_no;
    unsigned char death_script_opcode;
    short death_script_operand;
    unsigned char spell_mask_high;
};

/* One roster character's base stat line out of FRIAPRDA.DAT: race, class, starting level, base HP/MP/AP/DP/DX, movement, the initial learned-spell bitmap and the initial equipment and carried items. */
struct fdps_character_base_record {
    unsigned char race_id;
    unsigned char class_id;
    unsigned char level;
    short hp_base;
    short mp_base;
    unsigned char move;
    unsigned char spell_mask[4];
    unsigned char equipped_item_0;
    unsigned char equipped_item_1;
    unsigned char carried_items[4];
    short ap_base;
    short dp_base;
    short dx_base;
};

/* One FRILEVUP.DAT record: the per-level growth range of AP, DP, DX, HP and MP as five {min, exclusive max} byte pairs, plus the GETMGTAB.DAT spell-learning index for this character form. */
struct fdps_character_growth {
    unsigned char ap_min;
    unsigned char ap_max;
    unsigned char dp_min;
    unsigned char dp_max;
    unsigned char dx_min;
    unsigned char dx_max;
    unsigned char hp_min;
    unsigned char hp_max;
    unsigned char mp_min;
    unsigned char mp_max;
    unsigned char spell_learning_idx;
};

/* One PROEQU.DAT row: the six item type codes a character class is allowed to equip, in ascending order and padded with 0xFF. */
struct fdps_class_equip_record {
    unsigned char allowed_item_type[6];
};

/* One row of the PROMAP.DAT class table: the eight per-terrain movement costs, the class's critical rate and its magic-resistance complement. */
struct fdps_class_record {
    unsigned char move_cost[8];
    unsigned char critical;
    unsigned char magic_resist_complement;
};

/* The 50-byte DPMI real mode call structure DPMI function 0300h (Simulate Real Mode Interrupt) reads through ES:EDI and writes the returned register state back into; the game declares one instance to reach MSCDEX through INT 2Fh AX=1510h. */
struct fdps_dpmi_real_mode_call {
    unsigned int edi;
    unsigned int esi;
    unsigned int ebp;
    unsigned int reserved_by_system;
    unsigned int ebx;
    unsigned int edx;
    unsigned int ecx;
    unsigned int eax;
    unsigned short flags;
    unsigned short es;
    unsigned short ds;
    unsigned short fs;
    unsigned short gs;
    unsigned short ip;
    unsigned short cs;
    unsigned short sp;
    unsigned short ss;
};

/* One record of the enemy stat table loaded from ENEMYDAT.DAT; HP/MP/AP/DP/DX are per-level coefficients, race, class and MV are absolute. */
struct fdps_enemy_data {
    unsigned char race_id;
    unsigned char class_id;
    unsigned short hp;
    unsigned char mp;
    unsigned char ap;
    unsigned char dp;
    unsigned char dx;
    unsigned char mv;
    unsigned char exp_reward;
};

/* One record of the item table read out of the VFS member Item.dat: type, the four equipment stat modifiers, the weapon hit effect, the attack reach, the use effect and its parameters, and the shop price. */
struct fdps_item_effect {
    unsigned char type;
    short ap;
    short hit;
    short dp;
    short ev;
    unsigned char hit_effect;
    unsigned char hit_effect_rate;
    unsigned char range_min;
    unsigned char range_max;
    unsigned char use_effect;
    short use_amount;
    unsigned char use_distance;
    unsigned char use_target;
    unsigned char use_radius;
    unsigned short price;
    unsigned char select_mode;
    unsigned char gap_016[1];
};

/* M%02d.DTL map layer: fixed 0x10-byte header followed by width*height one-byte per-cell event codes. */
struct fdps_map_cell_code_layer {
    char magic[4];
    unsigned char version;
    unsigned short table_offset;
    short width;
    short height;
    unsigned char layer_count;
    unsigned char gap_00c[2];
    unsigned char layer_ids[2];
    unsigned char cells[1];
};

/* One entry of a map%02d.cod placement table: which character the entry is for and the tile it is placed on. */
struct fdps_map_spawn_pos_record {
    unsigned short char_id;
    short desired_x;
    short desired_y;
};

/* One tile of the per-battle movement/marking grid: zone-of-control flags plus the flood-fill marker; cell (x, y) lives at grid_base + 4 + 2 * (y * width + x). */
struct fdps_move_grid_cell {
    unsigned char flags;
    unsigned char marker;
};

/* One VGA DAC colour: red, green and blue as three 6-bit components in that order. A .PAL resource is 256 of these, and every palette the game uploads to the DAC is an array of this record. */
struct fdps_palette_entry {
    unsigned char red;
    unsigned char green;
    unsigned char blue;
};

/* One RankUp.dat record: the four class-change routes of one promotable character, each a 3-byte (portrait id, class id, movement bonus) triple -- no badge, 光之徽章, 暗之徽章, 勇者徽章. */
struct fdps_promotion_record {
    unsigned char default_portrait_id;
    unsigned char default_class_id;
    unsigned char default_move_bonus;
    unsigned char light_badge_portrait_id;
    unsigned char light_badge_class_id;
    unsigned char light_badge_move_bonus;
    unsigned char dark_badge_portrait_id;
    unsigned char dark_badge_class_id;
    unsigned char dark_badge_move_bonus;
    unsigned char hero_badge_portrait_id;
    unsigned char hero_badge_class_id;
    unsigned char hero_badge_move_bonus;
};

/* One record of the spell table read out of the VFS member MagicDat.dat: power (damage, heal, or a negative attack multiplier), hit rate, cast distance, blast radius, MP cost and target side. */
struct fdps_spell_effect {
    short power;
    unsigned char hit_rate;
    unsigned char cast_range_flags;
    unsigned char area;
    unsigned char mp_cost;
    unsigned char target_side;
};

/* One GetMgTab.dat record: the spell-learning schedule of one character form as six (level, spell id) byte pairs in ascending level order, an unused pair being (0xff, 0xff). */
struct fdps_spell_learning_record {
    unsigned char lv_0;
    unsigned char spell_id_0;
    unsigned char lv_1;
    unsigned char spell_id_1;
    unsigned char lv_2;
    unsigned char spell_id_2;
    unsigned char lv_3;
    unsigned char spell_id_3;
    unsigned char lv_4;
    unsigned char spell_id_4;
    unsigned char lv_5;
    unsigned char spell_id_5;
};

/* One tile id's row of a scene layer's ATTR<map><layer>.DAT attribute table: draw flags, translucency blend level, terrain class and combat backdrop id. */
struct fdps_tile_attr_entry {
    unsigned char flags;
    unsigned char blend_level;
    unsigned char terrain_type;
    unsigned char combat_backdrop_id;
};

/* One unit on the map: tile position, sprite state, side, inventory, spells, base stats and the derived combat stats; the element of both the map unit array and the party roster. */
struct fdps_unit_record {
    unsigned char pos_x;
    unsigned char pos_y;
    unsigned char sprite_cache_slot;
    unsigned char facing;
    unsigned char walk_step;
    unsigned char flags;
    unsigned char side;
    unsigned char portrait_id;
    unsigned char char_id;
    unsigned char reserved_09;
    unsigned char inventory_slots[16];
    unsigned char spells_known_bitmap[5];
    unsigned char race;
    unsigned char clazz;
    unsigned char level;
    unsigned char status_timers[6];
    unsigned char gap_028[9];
    unsigned char death_script_opcode;
    short death_script_operand;
    unsigned char ai_behavior;
    unsigned char ai_dest_x;
    unsigned char ai_dest_y;
    short ap_base;
    short dp_base;
    unsigned char move;
    unsigned char exp_carry;
    unsigned char event_slot;
    short dx_base;
    short hp_current;
    short hp_max;
    short mp_current;
    short mp_max;
    short ap;
    short dp;
    short hit;
    short ev;
};

/* VFS container header as the program models it: the first 11 bytes of a .vfs image, naming where the directory starts and how many 26-byte entries it has. The on-disk header runs 35 bytes; the 24-byte packer signature at +0x0b is outside this record because no instruction reads it. */
struct fdps_vfs_image_header {
    char magic[3];
    unsigned short version;
    unsigned short entry_table_offset;
    unsigned int entry_count;
};

/* One 0xa28-byte chapter save slot inside the decrypted FDE.SAV image at file offset 0x312b + slot * 0xa28: a copy of the 32-entry party roster whose tail carries the wall-clock stamp, followed by the chapter index, party size, gold and the four option toggles. */
struct fdps_save_slot {
    struct fdps_unit_record roster[31];
    unsigned char gap_9b0[60];
    unsigned int bonus_lottery_drawn_flag;
    unsigned int save_minute;
    unsigned int save_hour;
    unsigned int save_day;
    unsigned int save_month;
    unsigned char chapter_index;
    unsigned char roster_member_count;
    int party_gold;
    unsigned char terrain_hud_user_enabled;
    unsigned char battle_animation_enabled;
    unsigned char bgm_enabled_flag;
    unsigned char sfx_enabled_flag;
    unsigned char gap_a0a[30];
};

#pragma pack()

#endif
