// Ticket 23: give every game global the rebuild references a real definition,
// with the original image's initial contents, until the linker has nothing
// left to complain about.
//
// The worklist is the linker's. The first of the unit-test image's two links
// reports every symbol the emitted code references and nothing defines
// (tools/code_emit/build_emit.py -> workspace/code_emit/undefined.json), and
// every global on that list is one this ticket has not landed. Landing a
// definition takes it off the next build's list, so the loop is
//
//     link -> undefined globals -> one judge per global -> land -> link again
//
// and "done" is the list coming back empty, not a counter reaching a number.
//
// ADR-0007, rule by rule:
//
//   1. Judgements are written to files, summaries are returned. A judge writes
//      workspace/data_emit/verdicts/<symbol>.json and hands back ~200 bytes.
//      Whether a symbol is judged is decided by that file passing
//      tools/data_emit/land.py validate, never by the judge saying so.
//
//   2. Judges write nothing but their verdict: no src/, no Ghidra, no build.
//      Landing is tools/data_emit/land.py -- a script, so the transcription
//      cannot decide anything -- run by a mechanical Land stage. Ghidra
//      corrections the judges propose are applied by one bookkeeper at the end.
//
//   3. Every landing is followed by the gate: the build gate's emittest target,
//      which now includes tools/data_emit/check_data.py -- each landed global's
//      linked bytes against the shipped FDPS.LE, pointers compared by the name
//      of what they point at, plus the layout constraints the verdicts recorded.
//      A red gate goes to a Repair stage, then back through the gate.
//
//   4. Rescan. A judge sees one symbol; whether its neighbour forms one block
//      with it is often only clear once the neighbour has been read. Verdicts
//      left at low confidence or with an open question are read again after
//      every symbol of the round has a verdict, and this time the neighbours'
//      verdict files are admissible evidence.
//
//   5. Errors. One retry per judge; a symbol whose verdict still does not
//      validate is reported unfinished. A wave in which no agent returns at all
//      stops the run (5.2). Ghidra or the toolchain reported unreachable stops
//      it too (5.5). A landing the gate keeps rejecting is discarded and its
//      symbols reported, never committed. After a stop nothing downstream --
//      knowledge base, devlog narrative -- is written (5.6), only the report.
//      A re-run resumes: verdicts on disk are not re-judged (5.7).
//
// Interruption (ticket 21.6's rules, rebuild_info/emit_pipeline.md):
//
//   Recover runs first, because a usage limit kills the session where it
//   stands and no failure path of this script ever gets to tidy up. What it
//   may clean is bounded by path -- the paths this pipeline's stages write --
//   and anything dirty outside them stops the run.
//
//   The footprint. Ticket 22 marked the function in flight inside its tracked
//   state file. This ticket has no state file: its worklist is regenerated by
//   the linker every time, which is the point. So the footprint is its own
//   file, workspace/data_emit/in_flight.json, written by Land before it
//   touches src/ and removed once the landing is committed or discarded.
//   workspace/ is not tracked, so the marker is invisible to git status and
//   needs no place inside the boundary -- and it survives the kill that the
//   working-tree changes do not survive being cleaned. Judging needs no marker:
//   a judge that dies leaves no working-tree change and at most a verdict
//   file that fails validation, which puts the symbol straight back on the
//   list. So "killed mid-flight" can only mean a landing, and Recover reports
//   exactly those symbols, apart from the ones this run simply never reached.
//
// This workflow does not watch its own budget. It runs until the linker's
// list is empty, the caller's limit is used up, something upstream is broken,
// or it is killed.
//
// args: {
//   label:     string   run label, used in the devlog and run archive names
//   date:      string   YYYY-MM-DD, for the devlog file name (no Date here)
//   limit:     number   how many globals to judge this run (default: all)
//   passes:    number   link/judge/land passes before giving up (default 3)
// }

export const meta = {
  name: 'fdps-data-ticket23',
  description: 'Land every undefined FDPS global in src/ with its original contents: linker worklist, one judge per symbol, rescan, scripted landing, build gate plus byte check against FDPS.LE',
  phases: [
    { title: 'Recover', detail: 'clear what a killed run left inside the boundary' },
    { title: 'Worklist', detail: 'link, read the undefined globals' },
    { title: 'Judge', detail: 'one agent per global writes its verdict file' },
    { title: 'Rescan', detail: 're-read low-confidence verdicts with the neighbours in view' },
    { title: 'Reroute', detail: 'move a global to the file its layout neighbour lives in' },
    { title: 'Land', detail: 'land.py, build gate, byte check, commit' },
    { title: 'Repair', detail: 'diagnose a red gate' },
    { title: 'Ghidra', detail: 'apply the corrections the verdicts proposed' },
    { title: 'Knowledge', detail: 'rebuild_info/data_emit.md from the manifest' },
    { title: 'Report', detail: 'devlog and run archive' },
  ],
}

const REPO = 'C:\\Users\\fdpsf\\Documents\\fdps-anatomy'
const WS = REPO + '\\workspace\\data_emit'
const VERDICTS = WS + '\\verdicts'
const MARKER = WS + '\\in_flight.json'

const A = (typeof args === 'string' && args.length) ? JSON.parse(args) : (args || {})
const LABEL = A.label || 'data'
const DATE = A.date || 'undated'
const LIMIT = A.limit || 0
const PASSES = A.passes || 3
// Re-judging: globals already landed that a later finding says were decided on
// incomplete evidence. Each is judged again, one agent each, with the finding
// handed to it as evidence (not as a verdict to copy); what changes is landed
// and gated like anything else.
const REJUDGE = A.rejudge || []
const REJUDGE_NOTE = A.rejudgeNote || ''
const MAX_REPAIRS = 2
// Every commit message ends with these trailers, and is passed by file:
// PowerShell hands a multi-line -m argument to git as a pathspec.
const COAUTHOR = 'the two trailer lines "Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>" and '
  + '"Claude-Session: https://claude.ai/code/session_01SFBoWG1kt6hda9Cvf4BUr9". Write the whole message '
  + 'to a UTF-8 file under ' + REPO + '\\workspace\\data_emit\\ and commit with  git commit -F <file>  '
  + '(plus the pathspec where one is asked for); never a multi-line -m'

// The paths this pipeline's own stages write, and so the only ones Recover may
// clean (rebuild_info/data_emit.md, "中斷復原"). Reroute is the reason the
// routing files are in it; the Ghidra stage is the reason for the snapshot.
const BOUNDARY = [
  'src', 'tests', 'tools/data_emit/data', 'ghidra_snapshot',
  'tools/code_emit/build_routing.py', 'tools/code_emit/data/routing.json',
  'tools/code_emit/data/routing.md', 'rebuild_info/code_layout.md',
]
const B = BOUNDARY.join(' ')

// ---------------------------------------------------------------- schemas

const STOPS = {
  ghidra_unreachable: { type: 'boolean', description: 'A Ghidra MCP call still failed after one retry. Batch-wide stop.' },
  toolchain_unreachable: { type: 'boolean', description: 'The build could not run at all (DOSBox-X / Watcom / preflight). A build that runs and reports errors is NOT this.' },
  stop_detail: { type: 'string' },
}
const withStops = (p) => Object.assign({}, p, STOPS)

const RECOVER = {
  type: 'object', additionalProperties: false,
  required: ['tree_was_dirty', 'out_of_bounds', 'clean_now', 'interrupted'],
  properties: withStops({
    tree_was_dirty: { type: 'boolean' },
    out_of_bounds: { type: 'boolean' },
    out_of_bounds_paths: { type: 'array', items: { type: 'string' } },
    discarded_paths: { type: 'array', items: { type: 'string' } },
    interrupted: { type: 'array', items: { type: 'string' }, description: 'Symbols the in_flight marker named' },
    interrupted_since: { type: 'string' },
    residue_without_marker: { type: 'boolean' },
    snapshot_reexported: { type: 'boolean' },
    clean_now: { type: 'boolean' },
    note: { type: 'string' },
  }),
}

const WORKLIST = {
  type: 'object', additionalProperties: false,
  required: ['ok', 'globals_undefined', 'judge'],
  properties: withStops({
    ok: { type: 'boolean', description: 'worklist.py ran and printed JSON' },
    build_ok: { type: 'boolean' },
    globals_undefined: { type: 'integer' },
    not_globals: { type: 'array', items: { type: 'string' } },
    ready_to_land: { type: 'integer' },
    reroute: { type: 'array', items: { type: 'string' } },
    landed_but_undefined: { type: 'array', items: { type: 'string' } },
    judge: {
      type: 'array',
      description: 'The "judge" array verbatim, each row reduced to these fields',
      items: {
        type: 'object', additionalProperties: false,
        required: ['symbol', 'addr', 'target'],
        properties: {
          symbol: { type: 'string' }, addr: { type: 'string' }, type: { type: 'string' },
          size: { type: 'integer' }, segment: { type: 'string' }, target: { type: 'string' },
          readers: { type: 'array', items: { type: 'string' } },
          header: { type: 'array', items: { type: 'string' }, description: '"file: line" per extern' },
          verdict: { type: 'string' },
          handoff: { type: 'array', items: { type: 'string' } },
        },
      },
    },
    detail: { type: 'string' },
  }),
}

const JUDGE = {
  type: 'object', additionalProperties: false,
  required: ['symbol', 'wrote_verdict', 'status'],
  properties: withStops({
    symbol: { type: 'string' },
    wrote_verdict: { type: 'boolean' },
    validate_ok: { type: 'boolean', description: 'land.py validate printed ok for this symbol' },
    kind: { type: 'string' },
    confidence: { type: 'string' },
    layout: { type: 'string', description: 'none, or e.g. "follows X", "zero guard"' },
    reroute_to: { type: 'string' },
    header_change: { type: 'boolean' },
    open_questions: { type: 'integer' },
    status: { type: 'string', enum: ['done', 'blocked'] },
    note: { type: 'string' },
  }),
}

const SIMPLE = {
  type: 'object', additionalProperties: false,
  required: ['ok'],
  properties: withStops({
    ok: { type: 'boolean' },
    items: { type: 'array', items: { type: 'string' } },
    detail: { type: 'string' },
  }),
}

const LAND = {
  type: 'object', additionalProperties: false,
  required: ['applied', 'gate_pass', 'committed', 'tree_clean'],
  properties: withStops({
    applied: { type: 'boolean', description: 'land.py apply succeeded for every target' },
    landed: { type: 'array', items: { type: 'string' } },
    refused: { type: 'array', items: { type: 'string' }, description: '"symbol: reason" per refusal' },
    gate_pass: { type: 'boolean' },
    gate_detail: { type: 'string', description: 'Verbatim enough to act on: errors, failing tests, check_data failures' },
    committed: { type: 'boolean' },
    commit_line: { type: 'string' },
    discarded: { type: 'boolean', description: 'You discarded the landing (only when told to)' },
    marker_cleared: { type: 'boolean' },
    tree_clean: { type: 'boolean' },
  }),
}

const REPAIR = {
  type: 'object', additionalProperties: false,
  required: ['diagnosed', 'changed'],
  properties: withStops({
    diagnosed: { type: 'string', description: 'The cause, in one or two sentences' },
    changed: { type: 'array', items: { type: 'string' }, description: 'Files you changed (verdicts, tests)' },
    give_up_symbols: { type: 'array', items: { type: 'string' }, description: 'Symbols that cannot land in this batch; their entries must be pulled' },
    note: { type: 'string' },
  }),
}

const DONE = {
  type: 'object', additionalProperties: false,
  required: ['committed', 'summary'],
  properties: withStops({
    committed: { type: 'boolean' },
    written: { type: 'array', items: { type: 'string' } },
    summary: { type: 'string' },
  }),
}

// ---------------------------------------------------------------- prompts

const ENV = `FDPS.LE is a 1997 Traditional Chinese DOS game (Watcom C/C++ 10.0a, DOS/4G LE
module) being rebuilt into functionally equivalent C (ADR-0001). The repository
is ${REPO}. Ghidra has FDPS.LE open as the only program: leave the \`program\`
parameter empty on every MCP call. Load the Ghidra tools you need in ONE call:
  ToolSearch "select:mcp__ghidra__read_memory,mcp__ghidra__get_xrefs_to,mcp__ghidra__disassemble_function,mcp__ghidra__get_assembly_context,mcp__ghidra__search_instructions,mcp__ghidra__get_plate_comment,mcp__ghidra__decompile_function,mcp__ghidra__get_function_by_address"
If a Ghidra call fails, retry it ONCE. If the retry fails too, stop, set
ghidra_unreachable and put what you saw in stop_detail. Never set it for a blip
the retry cleared, and never guess what Ghidra would have said.
Use PowerShell for commands; Python writes and reads files as UTF-8. Do not use
PowerShell Get-Content/Set-Content on source or JSON files -- they corrupt UTF-8.`

const TOOLCHAIN_FACTS = `# What the toolchain does with a global (measured, tools/data_emit/layout_probe.py)
- An explicitly initialised global -- including "= 0" and "= { 0 }" -- goes to
  _DATA, in SOURCE ORDER within its .c, each object at its natural alignment:
  char 1, short 2, int and pointer 4, an array at its element's. Two 200-byte
  char arrays and an int defined in a row are exactly contiguous; a char
  followed by an int leaves three zero pad bytes.
- #pragma pack does NOT change where globals go. An unaligned layout (a short
  at an odd address, an int at address%4 != 0 right after a byte) cannot be
  reproduced with separate globals at all.
- A tentative definition ("int x;" with no initialiser) goes to _BSS in an
  order the toolchain chooses (measured: not source order). Never rely on it
  being next to anything (rebuild_info/pitfalls.md, contract B).
- land.py writes the initialised definitions of one .c in the ORIGINAL
  image's address order, then the zero ones. So two initialised symbols routed
  to the same .c whose original addresses are adjacent come out adjacent,
  provided the alignment above allows it.`

function judgePrompt(row, mode) {
  const handoff = (row.handoff || []).length
    ? row.handoff.join(', ') : 'none'
  const rejudge = row.verdict === 'rejudge' && REJUDGE_NOTE
  return [ENV, '', TOOLCHAIN_FACTS, '',
    '# Role: Judge one global. ' + (mode === 'retry'
      ? 'A previous attempt left no valid verdict for it; start over.' : ''),
    rejudge ? [
      '',
      '# This is a RE-judgement of a global that is already landed.',
      'Its current verdict is ' + VERDICTS + '\\' + row.symbol + '.json and its current',
      'definition is in src/. A later investigation produced the finding below. It is',
      'EVIDENCE, not a verdict to copy: check the parts that concern THIS symbol against',
      'the assembly yourself, then rewrite the verdict file from scratch under the rules',
      'below. If the finding does not hold for this symbol, say so in evidence and keep',
      'what was right. Record "rejudged": true and "previous_basis": <old basis>.',
      '',
      REJUDGE_NOTE,
    ].join('\n') : '',
    '',
    'Symbol   ' + row.symbol,
    'Address  ' + row.addr + '   routing type ' + (row.type || '?') + '   size ' + row.size
      + '   segment ' + (row.segment || '?'),
    'Target   src/' + row.target + '   (routing.json; rebuild_info/code_layout.md)',
    'Readers  ' + ((row.readers || []).join(', ') || '?'),
    'Header   ' + ((row.header || []).join(' | ') || '(none)'),
    'Handoff  ' + handoff,
    '',
    'You write exactly ONE file: ' + VERDICTS + '\\' + row.symbol + '.json',
    'Nothing else. No src/, no tests/, no Ghidra writes, no build (another stage',
    'is using DOSBox-X), no git. Reading anything is fine, including the object',
    'files under workspace\\code_emit\\out\\objs with',
    '  C:\\Users\\fdpsf\\Documents\\WATCOM_10_series\\WATCOM_10.0a\\BINNT\\WDISASM.EXE',
    '',
    '# What to settle',
    '',
    '1. CONTENTS. The definition must store exactly the image\'s initial bytes: read_memory',
    '   ' + row.addr + ' for ' + row.size + ' bytes (and a little either side for context). The gate',
    '   (tools/data_emit/check_data.py) compares the linked bytes with FDPS.LE byte for',
    '   byte, and a relocated pointer by the NAME of the function or data it points at.',
    '   So this is not a choice: all zero -> kind "zero", a tentative definition',
    '   ("int x;") unless point 3 needs it initialised; anything non-zero -> kind',
    '   "initialized" with those values. Spell values the way the type reads: signed',
    '   quantities as signed decimals, flags and masks in hex, a code-pointer table as',
    '   the function names (get_function_by_address on each slot; every name must be a',
    '   function src/ defines -- grep src/*.c). A code-pointer array is written with',
    '   the plain declarator, e.g.  void (*data_fdps_x_table[30])(void) = { ... };',
    '   exactly the type its header declares -- no typedef needed.',
    '',
    '2. TYPE. The definition\'s type must be the header\'s extern type exactly --',
    '   qualifiers (volatile) and element count included -- or the compile fails. Check',
    '   the header against the assembly anyway: access width, MOVSX vs MOVZX, JL/JG vs',
    '   JB/JA on the compares that read it (pitfalls.md contract C). If the header is',
    '   wrong, put the corrected extern in header.replace_with (header.current = the',
    '   line as it is now, verbatim) and write the definition in the corrected type.',
    '   Known case: data_fdps_battle_ai_best_physical_target_x is /uint in routing and',
    '   int in gamedata.h -- decide from the readers\' compares. A library type (union',
    '   REGS, struct SREGS) is spelled as the header spells it; list in "includes" any',
    '   project header (8.3 name) the target .c needs for the definition to compile.',
    '   The target\'s own header is included automatically.',
    '',
    '3. LAYOUT. Default: none. Record a constraint only with instruction-level',
    '   evidence that some reader or writer reaches THIS symbol through a NEIGHBOUR\'s',
    '   address or the other way round: an index past the end of a table, a cursor',
    '   that runs over the end of one array into the next, a block copy or struct',
    '   read that spans several symbols, a folded base that lands inside the previous',
    '   symbol (pitfalls.md contract H). Sweep with search_instructions for operands',
    '   near ' + row.addr + ' and read every xref (get_xrefs_to) -- all of them, not a sample.',
    '   If there is such a dependency:',
    '   - layout.follows = the symbol that must END exactly where this one starts (the',
    '     one before it in the original), with layout.why giving the instructions.',
    '     Both must be kind "initialized" (write "= 0" / "= { 0 }" for a zero one) and',
    '     routed to the SAME .c. If they are routed to different files, write',
    '     reroute = {to: "<the other one\'s file>", why} and keep target as routing',
    '     has it now; a separate stage moves it before landing.',
    '   - layout.zero_guard_before = true when the four bytes BELOW this symbol must be',
    '     zero storage the rebuild owns and nothing writes (a -1 index). The definition',
    '     then starts with its own static initialised zero dword, named for what it is,',
    '     immediately before the symbol, e.g.',
    '       static void *audio_sample_slot_below_table = 0;',
    '       void *data_fdps_audio_sample_handle_table[8] = { 0 };',
    '   - layout.zero_pad_after = N when a read runs N bytes past this symbol\'s end into',
    '     bytes the original holds as unreferenced zero padding (a byte flag read as a',
    '     dword). The definition then ENDS with its own static initialised zero array',
    '     of N bytes, named for what it is, e.g.',
    '       unsigned char data_fdps_x_flag = 0;',
    '       static unsigned char x_flag_dword_tail[3] = { 0, 0, 0 };',
    '     Otherwise those bytes are whatever the next module happens to start with.',
    '   - If the dependency needs a layout the toolchain cannot produce (see the facts',
    '     above: an unaligned field), say so in open_questions and set status blocked.',
    '   A symbol that only happens to sit next to another, with no code crossing the',
    '   boundary, has NO constraint. Inventing one costs nothing today and hides the',
    '   real ones.',
    '',
    '4. HANDOFF. Ticket 22 handed these concerns to this ticket: ' + handoff + '.',
    '   Read each in full:',
    '     python -c "import json;d=json.load(open(r\'' + REPO + '\\tools\\code_emit\\data\\emit_issues.json\',encoding=\'utf-8\'));a,n=\'<id>\'.split(\'#\');e=d[a][int(n)];print(e[\'what\']);print(e.get(\'answer\'))"',
    '   Whatever it requires of THIS symbol\'s definition (a value, a qualifier, a type,',
    '   an order, a guard) your verdict does, and handoff[] records {id, done: how}.',
    '   A requirement about a DIFFERENT symbol is that symbol\'s judge\'s job; note it',
    '   only if your own definition depends on it.',
    '',
    '5. GROUND TRUTH. If the symbol holds values a player sees (terrain bonuses, prices,',
    '   coordinates of things on screen, anything the strategy guide might list), look',
    '   for them: python tools/guide_scrape/guide_scrape.py search "<pattern>" --game fdps',
    '   and record guide = {applicable, result}. Not applicable is a fine answer; say why.',
    '',
    '6. GHIDRA. If Ghidra\'s type, name or plate comment for THIS symbol contradicts the',
    '   assembly, put the correction in ghidra_fixes (a list of plain instructions). You',
    '   do not apply it.',
    '',
    '# The verdict file (UTF-8 JSON, write it with Python)',
    '{',
    '  "symbol": "' + row.symbol + '", "addr": "' + row.addr + '", "target": "' + row.target + '",',
    '  "kind": "zero" | "initialized",',
    '  "definition": "the C text, e.g. int data_x = 15;  (C89, no extern, no #)",',
    '  "size": <bytes the symbol itself occupies, sizeof>,',
    '  "comment": "English, one to three sentences: what the initial value is and why it',
    '              matters. The header already says what the global IS; do not repeat it.",',
    '  "header": {"file": "x.h", "current": "<extern line verbatim>", "replace_with": null},',
    '  "includes": [],',
    '  "layout": {"follows": null, "zero_guard_before": false, "zero_pad_after": 0, "why": ""},',
    '  "reroute": null,',
    '  "handoff": [{"id": "...", "done": "..."}],',
    '  "guide": {"applicable": false, "result": "..."},',
    '  "confidence": "high" | "medium" | "low",',
    '  "basis": "one line: how it was classified (zero/initialised/layout) and on what",',
    '  "evidence": ["instruction addresses and what they show"],',
    '  "open_questions": [],',
    '  "ghidra_fixes": []',
    '}',
    'Then run, in the foreground:',
    '  cd ' + REPO + '; python tools/data_emit/land.py validate ' + row.symbol,
    'It must print "ok" (a reroute verdict prints the reroute and is fine). Fix the',
    'file until it does. Low confidence is honest and allowed; a confident guess is not.',
    '',
    'Your final message is the summary object and nothing else.',
  ].join('\n')
}

function rescanPrompt(sym) {
  return [ENV, '', TOOLCHAIN_FACTS, '',
    '# Role: Rescan one verdict (ADR-0007 rule 4).',
    '',
    'The verdict ' + VERDICTS + '\\' + sym + '.json was left at low confidence or with',
    'open questions. Its judge saw only this symbol. Every other undefined global now',
    'has a verdict in the same folder, and those files are admissible evidence: a',
    'neighbour\'s judge may have established what this one could not (that the two form',
    'one block, that a reader indexes across them, what a type really is). Citing a',
    'judgement somebody else already made is not making it for them.',
    '',
    'Read the verdict, its open questions, the neighbours\' verdicts by address, and',
    'Ghidra again where needed. Then rewrite the verdict file with what you can now',
    'settle, set "rescanned": true, and keep "first_pass" = the previous confidence.',
    'Rules 1-6 of the judge apply unchanged; you still write nothing but this file.',
    'A second look is not a reason to force a conclusion: what is still unknown stays',
    'in open_questions and the confidence stays low.',
    '',
    'Run  cd ' + REPO + '; python tools/data_emit/land.py validate ' + sym + '  and make it print ok.',
    'Your final message is the summary object and nothing else.',
  ].join('\n')
}

function recoverPrompt() {
  return [
    '# Role: Recovery. Mechanical; you judge nothing.',
    '',
    'A previous run may have been killed where it stood (a usage limit does that), so',
    'its tidy-up never ran. Clear what it left before anything starts.',
    '',
    '1. cd ' + REPO + '; git status --porcelain',
    '2. The paths this pipeline writes, and the only ones you may clean:',
    '     ' + BOUNDARY.join('  '),
    '   workspace/ is untracked and never appears; leave it alone -- the verdicts there',
    '   are what the re-run resumes from. ANY OTHER dirty path is out of bounds: change',
    '   nothing, discard nothing, set out_of_bounds with the paths verbatim, return.',
    '3. Read ' + MARKER + ' if it exists: it is the footprint a',
    '   landing writes before touching src/ and removes after committing or discarding.',
    '   Its "symbols" are what was in flight when the run died. Report them in',
    '   interrupted (and its "since" in interrupted_since), then delete the file.',
    '4. Discard in-bounds residue, all three commands, in this order:',
    '     git reset -q -- ' + B,
    '     git checkout -- ' + B,
    '     git clean -fd src tests tools/data_emit/data',
    '   The reset only unstages (pathspec reset, HEAD does not move); without it an',
    '   intent-to-add file survives checkout as zero bytes. Never revert, amend or move',
    '   anything committed.',
    '   If src/ or tests/ was dirty but the marker named nothing, discard anyway and set',
    '   residue_without_marker.',
    '5. If ghidra_snapshot/ was dirty the database may have been changed and saved',
    '   before the kill: after step 4, re-export instead of trusting either version:',
    '     ToolSearch "select:mcp__ghidra__run_ghidra_script"',
    '     run_ghidra_script ' + REPO + '\\tools\\ghidra_snapshot\\ExportGhidraSnapshot.java',
    '   then  git add ghidra_snapshot; git commit  with subject',
    '     data: 前一輪中斷，重新匯出 Ghidra 快照',
    '   a blank line, and  ' + COAUTHOR,
    '   Only if the export produced a diff.',
    '6. git status --porcelain must print nothing. Report clean_now.',
    '',
    'Your final message is the summary object and nothing else.',
  ].join('\n')
}

function worklistPrompt(build, symbols) {
  return [
    '# Role: Worklist. Run one command, report what it prints, judge nothing.',
    '',
    '  cd ' + REPO + '; python tools/data_emit/worklist.py' + (build ? ' --build' : '')
      + (symbols && symbols.length ? ' --symbols ' + symbols.join(',')
        : (LIMIT ? ' --limit ' + LIMIT : '')) + ' > ' + WS + '\\worklist.json',
    '  then read ' + WS + '\\worklist.json with Python (UTF-8).',
    build ? 'The --build rebuilds the unit-test image (several minutes, foreground). If it'
      + ' reports build_rc != 0, set build_ok false and copy build_tail into detail; if the'
      + ' build could not run at all (DOSBox-X or Watcom missing), set toolchain_unreachable.' : '',
    '',
    'Copy counts across, and the "judge" array row by row: symbol, addr, type, size,',
    'segment, target, readers, verdict, handoff, and header as "file: line" strings.',
    'Same order, nothing dropped. not_globals is the symbols of "not_globals" -- those',
    'are functions or unknown names, which this ticket does not own.',
    '',
    'Your final message is the summary object and nothing else.',
  ].join('\n')
}

function reroutePrompt(sym) {
  return [
    '# Role: Reroute one global. Mechanical: the decision is in the verdict.',
    '',
    'The verdict ' + VERDICTS + '\\' + sym + '.json asks for this global to be owned by',
    'another file because a layout neighbour lives there ("reroute": {to, why}).',
    '',
    '0. If tools/data_emit/data/manifest.json already lists this symbol, it is landed in',
    '   its old owner: take its definition out of that file\'s data block first,',
    '     python tools/data_emit/land.py remove --target <old owner .c> --addr <its addr>',
    '   (the Land stage writes it into the new owner from the verdict afterwards).',
    '1. In tools/code_emit/build_routing.py add to DATA_OVERRIDES, or replace the entry',
    '   if the symbol already has one:',
    '     "' + sym + '": ("<to>", "<the why, one line>"),',
    '   then  python tools/code_emit/build_routing.py  and  python tools/code_emit/build_routing.py --check',
    '   Never hand-edit routing.json or routing.md.',
    '2. The extern moves with ownership (rebuild_info/code_layout.md: the extern lives',
    '   in the owning .c\'s .h, once). Move its declaration and the comment above it',
    '   from the old owner\'s header to <to stem>.h, word for word. If the comment covers',
    '   other symbols too, split it honestly rather than moving a neighbour. Make every',
    '   .c that uses the symbol include the new header (grep src/*.c).',
    '3. If rebuild_info/code_layout.md states counts of globals per owner, fix them.',
    '4. In the verdict set target = <to> and reroute = null (Python, UTF-8). It is in',
    '   workspace/, not committed.',
    '5. python tools/code_emit/build_emit.py build  must succeed (foreground). If step 0',
    '   removed a definition, the symbol is briefly undefined and the build links it',
    '   from the stub module -- that is expected until Land writes it into its new owner.',
    '6. git add tools/code_emit src tools/data_emit/data rebuild_info/code_layout.md; git commit  with subject',
    '     data: ' + sym + ' 改由 <to> 擁有（佈局相鄰）',
    '   a blank line, one Traditional Chinese line on why, a blank line, ' + COAUTHOR,
    '7. git status --porcelain must be empty.',
    '',
    'Report ok=true only if committed and clean. Summary object only.',
  ].join('\n')
}

function landPrompt(batch, targets, mode) {
  const tlist = targets.join(' ')
  if (mode === 'discard') {
    return [
      '# Role: Land -- DISCARD mode. Throw this batch\'s landing away.',
      '',
      '  cd ' + REPO,
      '  git reset -q -- ' + B,
      '  git checkout -- ' + B,
      '  git clean -fd src tests tools/data_emit/data',
      'Then delete ' + MARKER + ' and confirm git status --porcelain is empty.',
      'Do not touch workspace/ otherwise and nothing committed.',
      'Report applied=false, gate_pass=false, committed=false, discarded=true,',
      'marker_cleared, tree_clean. Summary object only.',
    ].join('\n')
  }
  return [
    '# Role: Land. Mechanical: land.py decides nothing and neither do you.',
    '',
    'Batch ' + batch + ', targets: ' + tlist,
    '',
    (mode === 'reapply'
      ? '0. This is a re-application after a repair. Throw away the previous landing\'s\n'
        + '   src/ and manifest changes but KEEP the repair\'s tests/ edits:\n'
        + '     git reset -q -- src tools/data_emit/data\n'
        + '     git checkout -- src tools/data_emit/data\n'
        + '     git clean -fd src tools/data_emit/data\n'
        + '   The marker from the first attempt is still there; rewrite it in step 1.\n'
      : '0. git status --porcelain must be empty now. If it is not, stop and report.\n'),
    '1. Footprint FIRST, before src/ is touched. Write ' + MARKER,
    '   (Python, UTF-8): {"batch": "' + batch + '", "targets": [...], "symbols": [every',
    '   symbol land.py plan lists as ready for these targets], "since": <current date/time>}.',
    '   python tools/data_emit/land.py plan  gives the ready lists.',
    '2. For each target:  python tools/data_emit/land.py apply --target <t>',
    '   Record what it landed and what it refused ("symbol: reason"). A refusal is',
    '   reported, never worked around -- do not edit verdicts or src/ to make it pass.',
    '   An "error" (e.g. a layout order it cannot satisfy) means applied=false for the',
    '   whole batch: go straight to the report.',
    '3. The gate, foreground, both:',
    '     python tools/build_gate/gate.py check --target emittest',
    '   It builds, runs the unit tests and runs tools/data_emit/check_data.py (suite',
    '   data_emit.check), which compares every landed global with FDPS.LE. PASS means',
    '   the last line says PASS and no suite failed. On FAIL copy the errors, the',
    '   failing tests and the check_data failures (workspace/data_emit/check.json)',
    '   into gate_detail, verbatim enough for somebody else to act on, and STOP here:',
    '   do not commit, do not discard, leave the marker. Report.',
    '4. On PASS: git add src tests tools/data_emit/data; git commit  with subject',
    '     data: ' + batch + ' 落地 <n> 個全域（' + tlist + '），build gate 與原版比對通過',
    '   a blank line, one Traditional Chinese line listing the files, a blank line,',
    '   ' + COAUTHOR,
    '5. Delete the marker. git status --porcelain must be empty.',
    '',
    'Summary object only.',
  ].join('\n')
}

function repairPrompt(batch, detail, round) {
  return [ENV, '', TOOLCHAIN_FACTS, '',
    '# Role: Repair a red gate (round ' + round + ' of ' + MAX_REPAIRS + ').',
    '',
    'Batch ' + batch + ' was landed into the working tree (uncommitted) and the gate',
    'failed:',
    detail,
    '',
    'Find the cause. The legitimate fixes, and the only ones:',
    '- A verdict is wrong (a value, a type, a missing initialiser, a layout constraint,',
    '  a header line). Fix THAT symbol\'s verdict file, one symbol at a time, with the',
    '  same evidence standard as its judge (read the assembly; record in evidence what',
    '  you found). Never fix src/ directly -- the landing is re-applied from the verdicts.',
    '- A test asserted what the zero-filled stub used to give instead of setting up its',
    '  own state. The rule is rebuild_info/emit_pipeline.md "不准斷言 stub": the test',
    '  gets its own fixture (and restores the global when it leaves); its expectation',
    '  is never changed to whatever the code now happens to do.',
    '- A header extern that must change: through the verdict\'s header field.',
    'If a symbol cannot be made right, list it in give_up_symbols and delete its',
    'verdict\'s block entry by moving the verdict file to  ' + WS + '\\held\\  (Python).',
    'Do not run the gate yourself and do not commit; the Land stage re-applies and',
    're-gates. Do not touch anything outside the verdicts, tests/ and src/*.h.',
    '',
    'Summary object only.',
  ].join('\n')
}

function ghidraPrompt() {
  return [ENV, '',
    '# Role: Ghidra bookkeeper. Apply what the verdicts proposed; judge nothing new.',
    '',
    'cd ' + REPO + '; python tools/data_emit/land.py ghidra-fixes  lists the corrections',
    'landed verdicts proposed and nobody has applied. For each, apply it exactly',
    '(rename_data / apply_data_type / set_plate_comment as the text says; follow',
    '.claude/skills/ghidra-usage). One you cannot apply as written is reported in items,',
    'not reinterpreted. After each symbol, set "ghidra_applied": true in its verdict.',
    'Then: list_bookmarks(category="Bad Instruction") must be empty; save the program',
    '(save_program); re-export the snapshot:',
    '  run_ghidra_script ' + REPO + '\\tools\\ghidra_snapshot\\ExportGhidraSnapshot.java',
    'and if a label in the snapshot changed, python tools/code_emit/gen_types.py --check',
    'must still pass. Commit:  git add ghidra_snapshot; git commit  subject',
    '  data: 資料符號判定帶出的 Ghidra 修正',
    'a blank line, ' + COAUTHOR + '. Nothing to apply -> ok=true, commit nothing.',
    'git status --porcelain must end empty. Summary object only.',
  ].join('\n')
}

function knowledgePrompt(stats) {
  return [
    '# Role: Knowledge base. Write the conclusions, not the process.',
    '',
    'cd ' + REPO + '; python tools/data_emit/land.py summary  is the compact index of what',
    'landed. Read it, tools/data_emit/data/manifest.json, and CLAUDE.md\'s knowledge-base',
    'rules. Do NOT read the verdict files wholesale; open a single one only to quote a',
    'specific fact.',
    '',
    'Run stats: ' + JSON.stringify(stats),
    '',
    '1. rebuild_info/data_emit.md -- create or update. It owns: how a global\'s',
    '   definition is decided (contents = the image\'s initial bytes; type = its',
    '   header; zero vs initialised), the toolchain facts on layout (measured by',
    '   tools/data_emit/layout_probe.py -- run it if you need to see them again), the',
    '   block land.py writes and why its order is the layout, the layout constraints',
    '   that exist with their reason (a table of symbol / constraint / the reads that',
    '   need it), what check_data.py proves and what it cannot see, the footprint and',
    '   boundary rules of this pipeline, and counts by kind. Conclusions only, written',
    '   in Traditional Chinese; no dates, no "we first tried".',
    '2. rebuild_info/_index.md and README-level indexes: add the page.',
    '   tools/_index.md and tools/data_emit/_index.md (create: scripts, data, how to run).',
    '3. rebuild_info/pitfalls.md: any "written by intuition it would differ from the',
    '   original" found here (e.g. zero-looking initial values that are not zero, a',
    '   table read past its end, a guard below a table). Link to data_emit.md, do not',
    '   duplicate values. Check first that it is not already there.',
    '4. rebuild_info/emit_pipeline.md: the sections that say data arrives with ticket',
    '   23 now describe a past state; state the present one in a sentence each.',
    '5. Re-read every page you changed for process narration and remove it.',
    '6. Commit only those docs, with a pathspec:',
    '     git add <files>; git commit -F <msgfile> -- <files>',
    '   subject  docs: 票 23 資料符號的判定規則與佈局約束進知識庫 , a blank line, ' + COAUTHOR,
    'git status --porcelain must end empty. Summary object only.',
  ].join('\n')
}

function reportPrompt(report, stopped) {
  return [
    '# Role: Report. Write the run up and commit it.',
    '',
    'Run report (JSON): ' + JSON.stringify(report),
    '',
    '1. devlog/runs/' + DATE + '-data-' + LABEL + '.json -- the report above, verbatim,',
    '   pretty-printed (Python, UTF-8).',
    '2. devlog/' + DATE + '-data-' + LABEL + '.md -- follow devlog/_conventions.md: narrative in',
    '   Traditional Chinese, dead ends first. Say plainly: how many globals were judged,',
    '   landed, still undefined; which were interrupted in a previous run (the',
    '   "recovered" list) versus never reached this run (the "not_reached" list) --',
    '   they are different and must not be merged; every failure and why.',
    (stopped ? '   This run STOPPED early: ' + stopped + '. Say so in the first paragraph.' : ''),
    '3. git add devlog; git commit -F <msgfile> -- devlog   subject',
    '     devlog: 票 23 資料 emit ' + LABEL,
    '   a blank line, ' + COAUTHOR,
    'git status --porcelain must end empty. Summary object only.',
  ].join('\n')
}

// ------------------------------------------------------------ agent driver

class Stop extends Error {
  constructor(kind, detail) { super(kind + ': ' + detail); this.kind = kind; this.detail = detail }
}

function checkStops(out) {
  if (out && out.ghidra_unreachable === true) throw new Stop('ghidra_disconnect', out.stop_detail || '')
  if (out && out.toolchain_unreachable === true) throw new Stop('toolchain_unreachable', out.stop_detail || '')
  return out
}

// A single serial call: one retry, then null. Serial stages count a streak of
// nulls as the upstream signal (5.2), parallel waves count the whole wave.
let nullStreak = 0
async function serial(prompt, opts) {
  let out = await agent(prompt, opts)
  if (!out) {
    log('  ' + opts.label + ': no return, retrying once')
    out = await agent(prompt, opts)
  }
  if (!out) {
    nullStreak++
    if (nullStreak >= 2) throw new Stop('upstream_failure', 'two consecutive agent calls returned nothing')
    return null
  }
  nullStreak = 0
  return checkStops(out)
}

// A wave of independent judges. Returns the outputs aligned with rows (null
// for a missing one). Every agent null while at least one was sent means the
// cause is outside the workflow: stop, do not retry (5.2).
async function wave(rows, promptFn, label, phaseName, schema) {
  if (!rows.length) return []
  const outs = await parallel(rows.map((r) => () =>
    agent(promptFn(r), { label: label + ':' + (r.symbol || r), phase: phaseName, schema: schema })))
  const got = outs.filter(Boolean).length
  if (got === 0) throw new Stop('upstream_failure', 'no agent of a ' + rows.length + '-agent ' + label + ' wave returned')
  for (const o of outs) checkStops(o)
  return outs
}

// ------------------------------------------------------------------- run

const report = {
  label: LABEL, recovered: [], judged: 0, judge_failed: [], rescanned: 0,
  rerouted: [], batches: [], landed: [], land_failed: [], not_reached: [],
  still_undefined: null, stopped: null, notes: [],
}
let stopped = null

try {
  // ---------------------------------------------------------- Recover
  phase('Recover')
  const rec = await serial(recoverPrompt(), { label: 'recover', phase: 'Recover', schema: RECOVER })
  if (!rec) throw new Stop('recover_failed', 'the recovery stage returned nothing')
  if (rec.out_of_bounds) {
    report.stopped = 'dirty outside the boundary: ' + (rec.out_of_bounds_paths || []).join(', ')
    log('STOP: ' + report.stopped)
    return report
  }
  if (!rec.clean_now) throw new Stop('recover_failed', rec.note || 'tree not clean after recovery')
  report.recovered = rec.interrupted || []
  if (report.recovered.length) {
    log('recovery: a previous run was killed while landing ' + report.recovered.join(', ')
      + (rec.interrupted_since ? ' (since ' + rec.interrupted_since + ')' : '')
      + '; discarded, they return to the worklist')
  }
  if (rec.residue_without_marker) {
    report.notes.push('residue without a marker was discarded: ' + (rec.discarded_paths || []).join(', '))
  }

  const failedHere = {}          // symbol -> why, this run; not retried in later passes
  let lastUndefined = null
  let batchNo = 0
  let judgedCount = 0

  for (let pass = 1; pass <= PASSES; pass++) {
    // --------------------------------------------------------- Worklist
    phase('Worklist')
    const rejudgeNow = pass === 1 && REJUDGE.length
    const wl = await serial(worklistPrompt(true, rejudgeNow ? REJUDGE : null),
      { label: 'worklist:' + pass, phase: 'Worklist', schema: WORKLIST })
    if (!wl || !wl.ok) throw new Stop('worklist_failed', (wl && wl.detail) || 'no worklist')
    if (wl.build_ok === false) throw new Stop('build_failed', wl.detail || 'the build behind the worklist failed')
    lastUndefined = wl.globals_undefined
    if ((wl.landed_but_undefined || []).length) {
      report.notes.push('landed yet still undefined (manifest and link disagree): ' + wl.landed_but_undefined.join(', '))
    }
    log('pass ' + pass + ': ' + wl.globals_undefined + ' global(s) undefined, '
      + wl.judge.length + ' to judge, ' + (wl.ready_to_land || 0) + ' ready to land, '
      + (wl.reroute || []).length + ' reroute(s)')
    if (wl.globals_undefined === 0 && !rejudgeNow) break

    // ------------------------------------------------------------ Judge
    // The caller's limit is on how many globals this run judges, across passes.
    let toJudge = wl.judge.filter((r) => !failedHere[r.symbol])
    if (LIMIT) toJudge = toJudge.slice(0, Math.max(0, LIMIT - judgedCount))
    judgedCount += toJudge.length
    if (toJudge.length) {
      phase('Judge')
      const outs = await wave(toJudge, (r) => judgePrompt(r, 'first'), 'judge', 'Judge', JUDGE)
      report.judged += outs.filter(Boolean).length
      // Whether it is done is the file's business, not the judge's word.
      const check = await serial(
        '# Role: Check verdicts. Run and report, judge nothing.\n\n  cd ' + REPO
        + '; python tools/data_emit/land.py validate ' + toJudge.map((r) => r.symbol).join(' ')
        + '\n\nitems = every symbol whose line does NOT end in "ok" (a reroute line counts as ok).'
        + ' ok=true when the command ran. Summary object only.',
        { label: 'validate:' + pass, phase: 'Judge', schema: SIMPLE })
      const bad = new Set(((check && check.items) || []).map((s) => s.split(/\s/)[0]))
      const retry = toJudge.filter((r) => bad.has(r.symbol))
      if (retry.length) {
        log('retrying ' + retry.length + ' judge(s) whose verdict did not validate')
        await wave(retry, (r) => judgePrompt(r, 'retry'), 'rejudge', 'Judge', JUDGE)
        const check2 = await serial(
          '# Role: Check verdicts. Run and report, judge nothing.\n\n  cd ' + REPO
          + '; python tools/data_emit/land.py validate ' + retry.map((r) => r.symbol).join(' ')
          + '\n\nitems = every symbol whose line does NOT end in "ok" (a reroute line counts as ok).'
          + ' ok=true when the command ran. Summary object only.',
          { label: 'revalidate:' + pass, phase: 'Judge', schema: SIMPLE })
        for (const s of ((check2 && check2.items) || [])) {
          const sym = s.split(/\s/)[0]
          failedHere[sym] = 'no valid verdict after a retry'
          report.judge_failed.push(sym)
        }
      }
    }

    // ----------------------------------------------------------- Rescan
    phase('Rescan')
    const rl = await serial(
      '# Role: List. Run and report, judge nothing.\n\n  cd ' + REPO
      + '; python tools/data_emit/land.py rescan-list\n\nitems = the "symbol" of every row, in order.'
      + ' ok=true when it ran. Summary object only.',
      { label: 'rescan-list:' + pass, phase: 'Rescan', schema: SIMPLE })
    const rescan = ((rl && rl.items) || []).filter((s) => !failedHere[s])
    if (rescan.length) {
      log('rescanning ' + rescan.length + ' verdict(s)')
      const outs = await wave(rescan, (s) => rescanPrompt(s), 'rescan', 'Rescan', JUDGE)
      report.rescanned += outs.filter(Boolean).length
    }

    // ---------------------------------------------------------- Reroute
    const pl = await serial(
      '# Role: List. Run and report, judge nothing.\n\n  cd ' + REPO
      + '; python tools/data_emit/land.py plan\n\nitems = the "symbol" of every "reroute" row.'
      + ' detail = the "ready" object as compact JSON ({target: [symbols]}). ok=true when it ran.'
      + ' Summary object only.',
      { label: 'plan:' + pass, phase: 'Reroute', schema: SIMPLE })
    for (const sym of ((pl && pl.items) || [])) {
      if (failedHere[sym]) continue
      phase('Reroute')
      const rr = await serial(reroutePrompt(sym), { label: 'reroute:' + sym, phase: 'Reroute', schema: SIMPLE })
      if (rr && rr.ok) {
        report.rerouted.push(sym)
      } else {
        failedHere[sym] = 'reroute failed: ' + ((rr && rr.detail) || 'no return')
        report.land_failed.push(sym)
        await serial(landPrompt('reroute-' + sym, [], 'discard'), { label: 'discard:' + sym, phase: 'Reroute', schema: LAND })
      }
    }

    // ------------------------------------------------------------- Land
    const pl2 = await serial(
      '# Role: List. Run and report, judge nothing.\n\n  cd ' + REPO
      + '; python tools/data_emit/land.py plan\n\nitems = the keys of "ready" (target file names) that'
      + ' have at least one symbol. detail = the "ready" object as compact JSON. ok=true when it ran.'
      + ' Summary object only.',
      { label: 'plan-land:' + pass, phase: 'Land', schema: SIMPLE })
    let targets = ((pl2 && pl2.items) || [])
    if (!targets.length) {
      log('pass ' + pass + ': nothing ready to land')
    }
    // Everything ready in one landing first: one gate instead of thirty. If
    // that cannot be made green, fall back to one target at a time so a bad
    // verdict costs only its own file.
    const queue = targets.length ? [targets] : []
    while (queue.length) {
      const group = queue.shift()
      batchNo++
      const batch = LABEL + '-' + batchNo
      phase('Land')
      let land = await serial(landPrompt(batch, group, 'apply'), { label: 'land:' + batch, phase: 'Land', schema: LAND })
      let rounds = 0
      while (land && land.applied && !land.gate_pass && rounds < MAX_REPAIRS) {
        rounds++
        phase('Repair')
        const rep = await serial(repairPrompt(batch, land.gate_detail || '(no detail)', rounds),
          { label: 'repair:' + batch + ':' + rounds, phase: 'Repair', schema: REPAIR })
        for (const s of ((rep && rep.give_up_symbols) || [])) {
          failedHere[s] = 'held back by repair: ' + ((rep && rep.diagnosed) || '')
          report.land_failed.push(s)
        }
        phase('Land')
        land = await serial(landPrompt(batch, group, 'reapply'), { label: 'reland:' + batch + ':' + rounds, phase: 'Land', schema: LAND })
      }
      const row = { batch: batch, targets: group, landed: (land && land.landed) || [],
        refused: (land && land.refused) || [], gate_pass: !!(land && land.gate_pass),
        committed: !!(land && land.committed), repairs: rounds }
      if (land && land.committed && land.tree_clean) {
        report.landed.push(...row.landed)
        report.batches.push(row)
        log(batch + ': committed ' + row.landed.length + ' global(s) in ' + group.length + ' file(s)'
          + (rounds ? ' after ' + rounds + ' repair(s)' : ''))
        continue
      }
      // Not committed: throw the landing away, keep the tree clean for the next.
      row.detail = (land && land.gate_detail) || 'land returned nothing'
      report.batches.push(row)
      const dis = await serial(landPrompt(batch, group, 'discard'), { label: 'discard:' + batch, phase: 'Land', schema: LAND })
      if (!dis || !dis.tree_clean) throw new Stop('discard_failed', 'could not return the tree to clean after ' + batch)
      if (group.length > 1) {
        log(batch + ': gate stayed red; retrying one file at a time')
        for (const t of group) queue.push([t])
      } else {
        log(batch + ': ' + group[0] + ' could not be landed green; its symbols are reported unfinished')
        report.notes.push(group[0] + ': ' + row.detail.slice(0, 400))
        for (const s of row.landed) { failedHere[s] = 'gate red for ' + group[0]; report.land_failed.push(s) }
        if (!row.landed.length) failedHere['@' + group[0]] = 'gate red'
      }
    }
    if (!targets.length && !toJudge.length && !rescan.length) break
  }
  report.still_undefined = lastUndefined

  // Final link: the only honest answer to "is the list empty".
  phase('Worklist')
  const fin = await serial(worklistPrompt(true), { label: 'worklist:final', phase: 'Worklist', schema: WORKLIST })
  if (fin && fin.ok) {
    report.still_undefined = fin.globals_undefined
    report.not_reached = fin.judge.map((r) => r.symbol).filter((s) => !failedHere[s])
    report.unfinished = Object.keys(failedHere).map((s) => s + ' -- ' + failedHere[s])
  }

  // ------------------------------------------------------------ Ghidra
  phase('Ghidra')
  const gh = await serial(ghidraPrompt(), { label: 'ghidra', phase: 'Ghidra', schema: SIMPLE })
  if (!gh || !gh.ok) report.notes.push('ghidra bookkeeping: ' + ((gh && gh.detail) || 'no return'))

  // --------------------------------------------------------- Knowledge
  phase('Knowledge')
  const kb = await serial(knowledgePrompt({
    landed_this_run: report.landed.length, still_undefined: report.still_undefined,
    rerouted: report.rerouted, failed: report.land_failed.concat(report.judge_failed),
  }), { label: 'knowledge', phase: 'Knowledge', schema: DONE })
  if (!kb || !kb.committed) report.notes.push('knowledge stage did not commit: ' + ((kb && kb.summary) || 'no return'))
} catch (e) {
  if (e instanceof Stop) {
    stopped = e.kind + ' -- ' + e.detail
    report.stopped = stopped
    log('STOP: ' + stopped)
  } else {
    throw e
  }
}

// ------------------------------------------------------------ Report
// Written after a stop too (5.6: the report, never the downstream documents).
phase('Report')
const rp = await agent(reportPrompt(report, stopped), { label: 'report', phase: 'Report', schema: DONE })
if (!rp || !rp.committed) log('the report stage did not commit; the run report is in the return value')
return report
